### ISSUE TITLE
VLayout - Property 'column' does not exist on type ComponentOptions

### ISSUE THREAD

**Issue by Shinigami92** [chanlito/vuetify-tsx#5]
I have following code:

```tsx
<VLayout align-space-between justify-start column>
  //...
</VLayout>
```

Produces following error:

```
ERROR in .../index.tsx
30:5 Type '{ align-space-between: true; justify-start: true; column: true; }' is not assignable to type 'ComponentOptions<{ _tsxattrs: TsxComponentAttrs<Props, {}, {}>; } & Vue, DefaultData<{ _tsxattrs: TsxComponentAttrs<Props, {}, {}>; } & Vue>, DefaultMethods<{ _tsxattrs: TsxComponentAttrs<Props, {}, {}>; } & Vue>, DefaultComputed, PropsDefinition<...>, Record<...>>'.
  Property 'column' does not exist on type 'ComponentOptions<{ _tsxattrs: TsxComponentAttrs<Props, {}, {}>; } & Vue, DefaultData<{ _tsxattrs: TsxComponentAttrs<Props, {}, {}>; } & Vue>, DefaultMethods<{ _tsxattrs: TsxComponentAttrs<Props, {}, {}>; } & Vue>, DefaultComputed, PropsDefinition<...>, Record<...>>'.
    28 |        public render(): JSX.Element {
    29 |                return (
  > 30 |                        <VLayout align-space-between justify-start column>
       |                         ^
    31 |                                ...
```

I'm confused because in Props the column is defined as `boolean | undefined`.
And it is working! When I remove the `column` attribute, it renders in rows (as expected) and with `column` it renders in columns (as expected)

https://github.com/chanlito/vuetify-tsx/blob/master/src/VLayout.tsx#L7

**Comment by chanlito** [comment]
<img width="486" alt="Screen Shot 2019-06-09 at 9 30 36 AM" src="https://user-images.githubusercontent.com/15667259/59154291-485a0800-8a99-11e9-8d5b-758d9a056c00.png">

Seems fine here.

**Comment by Shinigami92** [comment]
I'll take a closer look and tell you later.  Unfortunately I have extremely many problems and test everything in a hobby project with the aim that we can use it AT work in production so that we have typescript support in 'html'/view files.

Currently I'm using class syntax.
Hopefully that has nothing to do with the problem.

**Comment by Shinigami92** [comment]
I really dont know what happend over night... ¯\_(ツ)_/¯
Works now?!
