### ISSUE TITLE
Provide examples in a different way

### ISSUE THREAD

**Issue by Shinigami92** [chanlito/vuetify-tsx#9]
Can you or we provide the examples from App.tsx in a different way?

I have two different suggestions:

### 1. We can create an "examples" folder at the same level as "src"

Advantages:

- There are no two different repositories to support
- Loosely coupled from the source code

Disadvantage:

- No real test / dependency usage (possibly side effects are overlooked)

### 2. You can create another repository "vuetify-tsx-demo" or "demo-vuetify-tsx"

Advantages:

- Real tested with dependency usage
- Completely decoupled from the source

Disadvantage:

- Maybe it will be outdated after a while, because we forgot it
- Wont be found so quickly by the community

**Comment by ST-DDT** [comment]
I would add it directly to the repo.
In a certain way, the sample projects are then the actual tests.
They offer some kind of holistic test scenario and reveal breaking changes for dependent projects early during the development and provide users with an up to date feeling on how the lib works and behaves.

**Comment by chanlito** [comment]
We could move the components to a `components` folder. We'll need to change how it's published to npm tho.

**Comment by Shinigami92** [comment]
I thought about it as well

So we could provide a structure like this:

- src
  - components
    - inputs
      - VTextField
      - ...
    - VDataTable
    - ...
- examples

This should be the same hierarchy as on https://vuetifyjs.com/en/getting-started/quick-start
